Updated get execution script tag function
ufcg-lsd/saps-common pull request #4
Opened 2020-07-06 13:20 UTC by wesleymonte

2020-07-06 19:05 UTC, raonismaneoto requested changes
Please, add some description about this pr purpose, it is not clear for me

2020-07-06 20:56 UTC, raonismaneoto approved these changes

2020-07-06 21:19 UTC, thiagoyeds approved these changes

2020-07-09 15:30 UTC, thiagomanel approved these changes
lgtm

2020-07-09 15:35 UTC, merged